### ISSUE TITLE
Cleanup of temporary and binary files

### ISSUE THREAD

**Issue by gsaponaro** [robotology/cfw002#1]
Hi @mbrunettini, I was having a look at this repository, and noticed the following temporary + binary files, probably they should not be committed:
- API/libcfw002.o
- module/.cfw002*
- module/*.o
- module/.tmp_versions
- tests/test_cfwlib, test_filter, test_audio, test_notblock, test_id_filter (executables)

Hope this helps.

**Comment by mbrunettini** [comment]
thanks.
fixed.
